routes/admin.php
<?php

Route::resource('series', 'SeriesController');
Route::resource('{series_by_id}/lessons', 'LessonsController')->except(['index', 'create', 'show', 'edit']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'FrontendController@welcome')->name('home');
Route::get('/profile/{user}', 'ProfilesController@index')->name('profile');
Route::get('/series', 'FrontendController@showAllseries')->name('series-all');
Route::get('/series/{series}', 'FrontendController@series')->name('series');
Route::get('/series/{series}/lesson/{lesson}', 'WatchSeriesController@showLesson')->name('series.watch.lesson');
Route::get('/register/confirm', 'ConfirmEmailController@index')->name('confirm-email');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::middleware('auth')->group(function () {
    Route::post('/profile/{user}', 'ProfilesController@update')->name('profile.update');
    Route::post('/profile/card/update', 'ProfilesController@cardUpdate')->name('profile.card.update');
    Route::get('/subscribe', 'SubscriptionsController@showSubscriptionForm')->name('subscription.form');
    Route::post('/subscribe', 'SubscriptionsController@subscribe')->name('subscribe');
    Route::post('/subscription/change', 'SubscriptionsController@change')->name('subscription.change');
    Route::get('/watch-series/{series}', 'WatchSeriesController@index')->name('series.watch');
    Route::post(
        '/series/complete-lesson/{lesson}',
        'WatchSeriesController@completeLesson'
    )->name('series.lesson.complete');
});

app/Http/Controllers/Admin/SeriesController.php
<?php

namespace Laracasts\Http\Controllers\Admin;

use Laracasts\Http\Controllers\Controller;
use Laracasts\Http\Requests\Series\SeriesCreateRequest;
use Laracasts\Http\Requests\Series\SeriesUpdateRequest;
use Laracasts\Series;

class SeriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.series.index')
            ->with('series', Series::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.series.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param SeriesCreateRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(SeriesCreateRequest $request)
    {
        return $request->uploadSeriesImage()
                       ->storeSeries();
    }

    /**
     * Display the specified resource.
     *
     * @param Series $series
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Series $series)
    {
        return view('admin.series.show')
            ->with('series', $series);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Series  $series
     * @return \Illuminate\Http\Response
     */
    public function edit(Series $series)
    {
        return view('admin.series.edit')
            ->with('series', $series);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param SeriesUpdateRequest $request
     * @param Series $series
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(SeriesUpdateRequest $request, Series $series)
    {
        return $request->updateSeries($series);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Series $series
     * @return \Illuminate\Http\JsonResponse
     * @throws \Exception
     */
    public function destroy(Series $series)
    {
        $series->delete();

        return response()->json(['status' => 'ok'], 200);
    }
}

resources/views/admin/series/create.blade.php
@extends('layouts.app')

@section('topbar')
    @include('template-parts.topbar', ['inverse' => true])
@endsection

@section('header')
    <header class="header header-inverse">
        <div class="container text-center">

            <div class="row">
                <div class="col-12 col-lg-8 offset-lg-2">

                    <h1>Create laracasts series</h1>
                    <p class="fs-20 opacity-70">Let's make the world a better place for coders</p>

                </div>
            </div>

        </div>
    </header>
@stop

@section('content')
    <div class="section bg-grey">
        <div class="container">

            <div class="row gap-y">
                <div class="col-12">

                    <form action="{{ route('series.store')  }}" method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <input class="form-control form-control-lg" type="text" name="title" placeholder="Your Series title">
                        </div>

                        <div class="form-group">
                            <input class="form-control form-control-lg" type="file" name="image">
                        </div>

                        <div class="form-group">
                            <textarea class="form-control form-control-lg" name="description" rows="4" placeholder="Your Description"></textarea>
                        </div>

                        <p>
                            <label class="custom-control custom-checkbox">
                                <input type="checkbox" name="featured" id="featured" class="custom-control-input">
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description"><strong>Featured</strong></span>
                            </label>
                        </p>

                        <button class="btn btn-lg btn-primary btn-block" type="submit">Create series</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/series/edit.blade.php
@extends('layouts.app')

@section('topbar')
    @include('template-parts.topbar', ['inverse' => true])
@endsection

@section('header')
    <header class="header header-inverse">
        <div class="container text-center">

            <div class="row">
                <div class="col-12 col-lg-8 offset-lg-2">

                    <h1>Edit: {{  $series->title }}</h1>
                    <p class="fs-20 opacity-70">Let's make the world a better place for coders</p>

                </div>
            </div>

        </div>
    </header>
@stop

@section('content')
    <div class="section bg-grey">
        <div class="container">

            <div class="row gap-y">
                <div class="col-12">

                    <form action="{{ route('series.update', $series->slug)  }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}

                        <div class="form-group">
                            <input class="form-control form-control-lg" type="text" value="{{ $series->title }}" name="title" placeholder="Your Series title">
                        </div>

                        <div class="form-group">
                            <input class="form-control form-control-lg" type="file" name="image">
                        </div>

                        <div class="form-group">
                            <textarea class="form-control form-control-lg" name="description" rows="4" placeholder="Your Description">{{ $series->description }}</textarea>
                        </div>

                        <p>
                            <label class="custom-control custom-checkbox">
                                <input type="checkbox" name="featured" id="featured" class="custom-control-input">
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description"><strong>Featured</strong></span>
                            </label>
                        </p>

                        <button class="btn btn-lg btn-primary btn-block" type="submit">Update series</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/series/index.blade.php
@extends('layouts.app')

@section('topbar')
    @include('template-parts.topbar', ['inverse' => true])
@endsection

@section('header')
    <header class="header header-inverse">
        <div class="container text-center">

            <div class="row">
                <div class="col-12 col-lg-8 offset-lg-2">

                    <h1>All series</h1>
                    <p class="fs-20 opacity-70">Let's make the world a better place for coders</p>

                </div>
            </div>

        </div>
    </header>
@stop

@section('content')
    <div class="section bg-grey">
        <div class="container bg-white b-1 border-secondary">

            <div class="row gap-y">
                <div class="col-12">

                    <vue-series init_series="{{ $series }}"></vue-series>

                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/series/show.blade.php
@extends('layouts.app')

@section('topbar')
    @include('template-parts.topbar', ['inverse' => true])
@endsection

@section('header')
    <header class="header header-inverse">
        <div class="container text-center">

            <div class="row">
                <div class="col-12 col-lg-8 offset-lg-2">

                    <h1>{{ $series->title }}</h1>
                    <p class="fs-20 opacity-70">Customize your series lessons</p>

                </div>
            </div>

        </div>
    </header>
@stop

@section('content')
    <div class="section bg-gray">
        <div class="container">

            <div class="row gap-y">
                <div class="col-12">

                    <vue-lessons data-series="{{ $series }}" data-lessons="{{ $series->lessons }}"></vue-lessons>

                </div>
            </div>
        </div>
    </div>
@stop