routes/admin.php
<?php

Route::resource('series', 'SeriesController');
Route::resource('{series_by_id}/lessons', 'LessonsController')->except(['index', 'create', 'show', 'edit']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'FrontendController@welcome')->name('home');
Route::get('/profile/{user}', 'ProfilesController@index')->name('profile');
Route::get('/series', 'FrontendController@showAllseries')->name('series-all');
Route::get('/series/{series}', 'FrontendController@series')->name('series');
Route::get('/series/{series}/lesson/{lesson}', 'WatchSeriesController@showLesson')->name('series.watch.lesson');
Route::get('/register/confirm', 'ConfirmEmailController@index')->name('confirm-email');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::middleware('auth')->group(function () {
    Route::post('/profile/{user}', 'ProfilesController@update')->name('profile.update');
    Route::post('/profile/card/update', 'ProfilesController@cardUpdate')->name('profile.card.update');
    Route::get('/subscribe', 'SubscriptionsController@showSubscriptionForm')->name('subscription.form');
    Route::post('/subscribe', 'SubscriptionsController@subscribe')->name('subscribe');
    Route::post('/subscription/change', 'SubscriptionsController@change')->name('subscription.change');
    Route::get('/watch-series/{series}', 'WatchSeriesController@index')->name('series.watch');
    Route::post(
        '/series/complete-lesson/{lesson}',
        'WatchSeriesController@completeLesson'
    )->name('series.lesson.complete');
});

app/Series.php
<?php

namespace Laracasts;

use Illuminate\Database\Eloquent\Model;

class Series extends Model
{
    protected $guarded = ['slug'];

    protected $with = ['lessons'];

    /**
     * Autofill slug
     */
    public static function boot()
    {
        parent::boot();

        self::creating(function ($model) {
            $model->slug = slugify($model->title);
        });

        self::updating(function ($model) {
            $model->slug = slugify($model->title);
        });

        self::saving(function ($model) {
            $model->slug = slugify($model->title);
        });
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * Lesson belongs to a user
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Series has many lessons
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function lessons()
    {
        return $this->hasMany(Lesson::class);
    }

    /**
     * Return the public path for series image
     *
     * @return string
     */
    public function getImagePathAttribute()
    {
        return asset('storage' . $this->image_url);
    }

    /**
     * Get ascending ordered lessons by episode number
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getOrderedLessons()
    {
        return $this->lessons()->orderBy('episode_number', 'asc')->get();
    }
}

resources/views/template-parts/series.blade.php
<div class="card mb-30">
    <div class="row">
        <div class="col-12 col-md-4 align-self-center">
            <a href=""><img src="{{ $series->image_path }}" alt="..."></a>
        </div>

        <div class="col-12 col-md-8">
            <div class="card-block">
                <h4 class="card-title">{{ $series->title }}</h4>
                <p class="card-subtitle"><small>Author: <a href="{{ route('profile', $series->user_id) }}">{{ $series->user->name }}</a></small></p>

                <p class="card-text">{{ $series->description }}</p>
                <a class="fw-600 fs-12" href="{{ route('series', $series->slug) }}">Read more <i class="fa fa-chevron-right fs-9 pl-8"></i></a>
            </div>
        </div>
    </div>
</div>

resources/views/template-parts/topbar.blade.php
@php
    $isInverse = $inverse ?? false;
@endphp

<nav class="topbar topbar-expand-md topbar-sticky @if($isInverse) topbar-inverse @endif">
    <div class="container">

        <div class="topbar-left">
            <button class="topbar-toggler">&#9776;</button>
            <a class="topbar-brand" href="/">
                LARACASTS
            </a>
        </div>


        <div class="topbar-right">
            <ul class="topbar-nav nav nav-navbar">
                @auth
                    @admin
                        <li class="nav-item"><a href="{{ route('series.index') }}" class="nav-link">All Series</a></li>
                        <li class="nav-item"><a href="{{ route('series.create') }}" class="nav-link">Create Series</a></li>
                    @endadmin

                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('profile', auth()->user()->id) }}">
                        Hey {{ auth()->user()->name }}
                        </a>
                        <nav class="nav-submenu">
                            @if(!auth()->user()->subscribed())
                                <a href="{{ route('subscribe') }}" class="nav-link">Subscribe</a>
                            @endif
                            <a href="{{ route('logout') }}" class="nav-link">Logout</a>
                        </nav>
                    </li>
                @endauth

                @guest
                    <li class="nav-item"><a href="{{ route('series-all') }}" class="nav-link">All Series</a></li>

                    @if(Request::route()->getName() !== 'login')
                        <li class="nav-item"><a class="nav-link" href="javascript:;" data-toggle="modal" data-target="#loginModal">Login</a></li>
                    @endif
                @endguest
            </ul>
        </div>

    </div>
</nav>